# Generated by Django 2.2.14 on 2021-03-14 15:52

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('upload_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=100)),
                ('participants', picklefield.fields.PickledObjectField(default=[], editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('upload_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
